title: TOTP
email: whdzera@gmail.com
description: >-
  A Time-based One-Time Password (TOTP) generator
baseurl: "/totp"
url: ""

include:
  - app

exclude:
  - spec
  - package.json
  - package-lock.json
  - README.md
  - Rakefile
  - vite.config.js
